# aion-gate PROD (порт 2106 — оригинального гейта; свитч 06.10) — зеркало config.txt 41007
serverPort: 2106
authAddr: 127.0.0.1
authPort: 2110
numThread: 32
numIOThread: 96
acceptCallNum: 200
socketLimit: 2000
sessionTimeout: 5
useForbiddenIPList: true
blockIPsFile: etc/BlockIPs.txt
logDirectory: log
checkGameGuard: false
useGameGuard: false
useNotifyCSResult: true
loginType: 2
companyCode: "2"
logdport: 3999
useLogd: false
tryInterval: 60
tryCount: 20
tryBlockInterval: 120
dumpPacket: false
ggNumActive: 50
useGCSideExtendAccount: true
appLaunchBanDelay: 5
useReportMail: false
authReconnectInterval: 30
welcomeB0: 101
welcomeB1: 114
welcomeB2: 0
ship:
  enabled: false