#!/usr/bin/env python3
"""Генерация internal/proto/blowfish_const.go + тест-векторов для aion-gate.
P/S — стандартные пи-константы Blowfish из .rdata AuthGateD (@0x437570/@0x4375b8).
Векторы — через pip-модуль blowfish (кросс-проверка Go-реализации).
Запуск из корня репо: python3 tools/analysis/gen_blowfish_const.py
"""
import json, os, random, struct, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EXE = os.path.join(REPO, 'tools/analysis/AuthGateD_original.exe')
PROTO = os.path.join(REPO, 'nextgen/aion-gate/internal/proto')

d = open(EXE, 'rb').read()
P = d[0x37570:0x37570 + 72]          # 18 u32 LE
S = d[0x375b8:0x375b8 + 4096]        # 4×256 u32 LE
assert struct.unpack('<I', P[:4])[0] == 0x243f6a88, 'P[0] != 0x243f6a88'
assert struct.unpack('<I', S[:4])[0] == 0xd1310ba6, 'S[0][0] != 0xd1310ba6'

hexs = (P + S).hex()
assert len(hexs) == (72 + 4096) * 2
lines = [hexs[i:i + 120] for i in range(0, len(hexs), 120)]
go = '// Code generated by tools/analysis/gen_blowfish_const.py из AuthGateD_original.exe\n'
go += '// (.rdata: P@0x437570, S@0x4375b8, u32 LE). НЕ редактировать вручную.\npackage proto\n\n'
go += 'import "encoding/hex"\n\nconst piosHex = `' + ''.join(lines) + '`\n\n'
go += '''func mustParsePIOS() (p [18]uint32, s [4][256]uint32) {
	b, err := hex.DecodeString(piosHex)
	if err != nil {
		panic(err)
	}
	if len(b) != 72+4096 {
		panic("pios size")
	}
	le := func(o int) uint32 {
		return uint32(b[o]) | uint32(b[o+1])<<8 | uint32(b[o+2])<<16 | uint32(b[o+3])<<24
	}
	for i := 0; i < 18; i++ {
		p[i] = le(i * 4)
	}
	for i := 0; i < 1024; i++ {
		s[i/256][i%256] = le(72 + i*4)
	}
	return p, s
}
'''
os.makedirs(PROTO, exist_ok=True)
open(os.path.join(PROTO, 'blowfish_const.go'), 'w').write(go)
print('blowfish_const.go:', len(go), 'bytes')

# Векторы ECB (кросс-проверка Go vs python-blowfish)
import blowfish
random.seed(7)
vecs = []
for i in range(8):
    key = bytes(random.randrange(256) for _ in range([4, 8, 12, 16][i % 4]))
    pt = bytes(random.randrange(256) for _ in range(8))
    c = blowfish.Cipher(key)
    ct = next(c.encrypt_ecb(pt))
    assert next(c.decrypt_ecb(ct)) == pt
    vecs.append({'key': key.hex(), 'pt': pt.hex(), 'ct': ct.hex()})
os.makedirs(os.path.join(PROTO, 'testdata'), exist_ok=True)
json.dump(vecs, open(os.path.join(PROTO, 'testdata', 'blowfish-vectors.json'), 'w'))
print('vectors:', len(vecs))

# Копия LUT рядом с package (для go:embed)
import shutil
shutil.copy(os.path.join(REPO, 'nextgen/aion-gate/testdata/gate-lut-0x437160.bin'),
            os.path.join(PROTO, 'testdata/gate-lut.bin'))
print('gate-lut.bin: copied')
